from __future__ import annotations

from .types import Config, ImageU8


def apply_geometry(arr_u8: ImageU8, geometry_cfg: Config) -> tuple[ImageU8, list[str]]: ...
def assert_geometry_unchanged(before_u8: ImageU8, after_u8: ImageU8) -> None: ...
def enforce_no_geometry_change_policy(safety_cfg: Config, geometry_cfg: Config) -> None: ...
def estimate_translation_pixels(ref_u8: ImageU8, cand_u8: ImageU8) -> tuple[float, float]: ...
